export interface AcademyItem {
  name: string;
  bgPos: string;
}

export const academyItemBgUrl =
  'https://gppl.innogamescdn.com/images/game/autogenerated/research/research_50x50_2.99.png';

export const academyItems: Record<string, AcademyItem> = {
  slinger: { name: 'slinger', bgPos: '-3950px 0' },
  archer: { name: 'archer', bgPos: '-50px 0' },
  town_guard: { name: 'town_guard', bgPos: '-4750px 0' },
  hoplite: { name: 'hoplite', bgPos: '-2650px 0' },
  meteorology: { name: 'meteorology', bgPos: '-2950px 0' },
  espionage: { name: 'espionage', bgPos: '-2450px 0' },
  booty_bpv: { name: 'booty_bpv', bgPos: '-750px 0' },
  pottery: { name: 'pottery', bgPos: '-3350px 0' },
  rider: { name: 'rider', bgPos: '-3550px 0' },
  architecture: { name: 'architecture', bgPos: '-150px 0' },
  instructor: { name: 'instructor', bgPos: '-2750px 0' },
  bireme: { name: 'bireme', bgPos: '-550px 0' },
  building_crane: { name: 'building_crane', bgPos: '-950px 0' },
  shipwright: { name: 'shipwright', bgPos: '-3750px 0' },
  colonize_ship: { name: 'colonize_ship', bgPos: '-1550px 0' },
  chariot: { name: 'chariot', bgPos: '-1350px 0' },
  attack_ship: { name: 'attack_ship', bgPos: '-250px 0' },
  conscription: { name: 'conscription', bgPos: '-1750px 0' },
  demolition_ship: { name: 'demolition_ship', bgPos: '-2150px 0' },
  catapult: { name: 'catapult', bgPos: '-1150px 0' },
  cryptography: { name: 'cryptography', bgPos: '-1850px 0' },
  small_transporter: { name: 'small_transporter', bgPos: '-4050px 0' },
  plow: { name: 'plow', bgPos: '-3250px 0' },
  berth: { name: 'berth', bgPos: '-350px 0' },
  trireme: { name: 'trireme', bgPos: '-4850px 0' },
  phalanx: { name: 'phalanx', bgPos: '-3050px 0' },
  breach: { name: 'breach', bgPos: '-850px 0' },
  mathematics: { name: 'mathematics', bgPos: '-2850px 0' },
  ram: { name: 'ram', bgPos: '-3450px 0' },
  cartography: { name: 'cartography', bgPos: '-1050px 0' },
  take_over: { name: 'take_over', bgPos: '-4450px 0' },
  stone_storm: { name: 'stone_storm', bgPos: '-4150px 0' },
  temple_looting: { name: 'temple_looting', bgPos: '-4650px 0' },
  divine_selection: { name: 'divine_selection', bgPos: '-2350px 0' },
  combat_experience: { name: 'combat_experience', bgPos: '-1650px 0' },
  strong_wine: { name: 'strong_wine', bgPos: '-4250px 0' },
  set_sail: { name: 'set_sail', bgPos: '-3650px 0' },
};
